// Re-export Aygent schema tables used by tools
export {
  aygentProjects,
  aygentLeads,
  aygentActivities,
  aygentTags,
  aygentLeadTags,
  aygentWhatsappMessages,
  aygentWhatsappTemplates,
  aygentViewings,
  aygentCampaigns,
  aygentCampaignSteps,
  aygentCampaignEnrollments,
  aygentDldTransactions,
  aygentListingWatches,
  aygentLandlords,
  aygentProperties,
  aygentTenancies,
  aygentPortals,
  aygentPortalActivity,
  aygentDocuments,
  aygentAgentMemory,
  aygentGuardrails,
  aygentNews,
  aygentCallLogs,
  aygentCallConfigs,
  aygentCallScripts,
  aygentAgentCredentials,
} from "@paperclipai/db";
