import {
  pgTable,
  uuid,
  text,
  real,
  integer,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";

export const aygentDldTransactions = pgTable(
  "aygent_dld_transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    transactionId: text("transaction_id"),
    procedureNameEn: text("procedure_name_en"),
    projectNameEn: text("project_name_en"),
    actualWorth: real("actual_worth"),
    propertyUsageEn: text("property_usage_en"),
    instanceDate: text("instance_date"),
    buildingNameEn: text("building_name_en"),
    transGroupEn: text("trans_group_en"),
    propertyTypeEn: text("property_type_en"),
    propertySubTypeEn: text("property_sub_type_en"),
    roomsEn: text("rooms_en"),
    areaNameEn: text("area_name_en"),
    regTypeEn: text("reg_type_en"),
    masterProjectEn: text("master_project_en"),
    meterSalePrice: real("meter_sale_price"),
    nearestMetroEn: text("nearest_metro_en"),
    nearestMallEn: text("nearest_mall_en"),
    nearestLandmarkEn: text("nearest_landmark_en"),
    hasParking: boolean("has_parking"),
    noOfBuyers: integer("no_of_buyers"),
    noOfSellers: integer("no_of_sellers"),
    unitNumber: text("unit_number"),
    pricePerSqft: real("price_per_sqft"),
    sizeSqft: real("size_sqft"),
    source: text("source"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    areaNameIdx: index("aygent_dld_area_name_idx").on(table.areaNameEn),
    transGroupIdx: index("aygent_dld_trans_group_idx").on(table.transGroupEn),
    instanceDateIdx: index("aygent_dld_instance_date_idx").on(table.instanceDate),
    propertySubTypeIdx: index("aygent_dld_property_sub_type_idx").on(table.propertySubTypeEn),
    areaDateIdx: index("aygent_dld_area_date_idx").on(table.areaNameEn, table.instanceDate),
    buildingDateIdx: index("aygent_dld_building_date_idx").on(table.buildingNameEn, table.instanceDate),
    sourceIdx: index("aygent_dld_source_idx").on(table.source),
  }),
);
