import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  index,
  real,
  boolean,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";

export const aygentProjects = pgTable(
  "aygent_projects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    reellyId: integer("reelly_id"),
    name: text("name").notNull(),
    developer: text("developer"),
    description: text("description"),
    shortDescription: text("short_description"),
    district: text("district"),
    region: text("region"),
    city: text("city"),
    sector: text("sector"),
    location: text("location"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    minPrice: real("min_price"),
    maxPrice: real("max_price"),
    minSize: real("min_size"),
    maxSize: real("max_size"),
    priceCurrency: text("price_currency"),
    areaUnit: text("area_unit"),
    constructionStatus: text("construction_status"),
    saleStatus: text("sale_status"),
    completionDate: text("completion_date"),
    completionDatetime: timestamp("completion_datetime", { withTimezone: true }),
    readinessProgress: real("readiness_progress"),
    furnishing: text("furnishing"),
    serviceCharge: real("service_charge"),
    escrowNumber: text("escrow_number"),
    postHandover: boolean("post_handover"),
    buildingCount: integer("building_count"),
    unitsCount: integer("units_count"),
    amenities: jsonb("amenities").$type<string[]>().default([]),
    paymentPlans: jsonb("payment_plans").$type<Record<string, unknown>[]>().default([]),
    nearbyLandmarks: jsonb("nearby_landmarks").$type<Record<string, unknown>[]>().default([]),
    buildings: jsonb("buildings").$type<Record<string, unknown>[]>().default([]),
    parkings: jsonb("parkings").$type<Record<string, unknown>[]>().default([]),
    unitBreakdown: jsonb("unit_breakdown").$type<Record<string, unknown>[]>().default([]),
    coverImageUrl: text("cover_image_url"),
    brochureUrl: text("brochure_url"),
    floorPlanUrl: text("floor_plan_url"),
    generalPlanUrl: text("general_plan_url"),
    images: jsonb("images").$type<string[]>().default([]),
    brand: text("brand"),
    managingCompany: text("managing_company"),
    isPartnerProject: boolean("is_partner_project").default(false),
    syncedAt: timestamp("synced_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyIdx: index("aygent_projects_company_idx").on(table.companyId),
    developerIdx: index("aygent_projects_developer_idx").on(table.developer),
    districtIdx: index("aygent_projects_district_idx").on(table.district),
    saleStatusIdx: index("aygent_projects_sale_status_idx").on(table.saleStatus),
    priceRangeIdx: index("aygent_projects_price_range_idx").on(table.minPrice, table.maxPrice),
    companyReellyIdx: uniqueIndex("aygent_projects_company_reelly_idx").on(table.companyId, table.reellyId),
  }),
);
